listen: :8080
docPath: /opt/doc
db:
  host: localhost
  port: 5432
  user: postgres
  password: docker
  name: mvvm
microservices:
  auth:
    host: 127.0.0.1
    port: 8081
  vacancy:
    host: localhost
    port: 8082
